'use client';

import React, { useState, useMemo } from 'react';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription, SheetFooter } from '@/components/ui/sheet';
import { Button } from '@/components/ui/button';
import { useToast } from '@/hooks/use-toast';
import { type VpnConfig, type Device } from '@/lib/types';
import { Textarea } from '../ui/textarea';
import QRCode from 'qrcode.react';
import { Copy, Download, RefreshCw } from 'lucide-react';
import { v4 as uuidv4 } from 'uuid'; // Mock for key generation

interface VpnClientConfigGeneratorProps {
  isOpen: boolean;
  onClose: () => void;
  serverConfig: VpnConfig;
  device: Device;
}

// Mock key generation. In a real scenario, this would use a proper crypto library
// or be generated by the `wg` command-line tool.
const generateMockKeys = () => {
    const privateKey = btoa(uuidv4() + uuidv4()).substring(0, 43) + '=';
    const publicKey = btoa(privateKey).substring(0, 43) + '='; // Not cryptographically correct, for demo only
    return { privateKey, publicKey };
}

const VpnClientConfigGenerator: React.FC<VpnClientConfigGeneratorProps> = ({ isOpen, onClose, serverConfig, device }) => {
    const { toast } = useToast();
    const [clientKeys, setClientKeys] = useState(generateMockKeys);

    const clientConfigText = useMemo(() => {
        // In a real implementation, you would need the server's public key.
        // We will use a placeholder for this demo.
        const serverPublicKey = 'SERVER_PUBLIC_KEY_PLACEHOLDER';

        return `[Interface]
PrivateKey = ${clientKeys.privateKey}
Address = 10.0.0.2/32
DNS = 1.1.1.1

[Peer]
PublicKey = ${serverPublicKey}
AllowedIPs = 0.0.0.0/0
Endpoint = ${device.ip}:${serverConfig.listenPort}
PersistentKeepalive = 25
`;
    }, [clientKeys, serverConfig, device]);

    const handleCopy = () => {
        navigator.clipboard.writeText(clientConfigText);
        toast({ title: 'Copied!', description: 'Client config copied to clipboard.' });
    };

    const handleDownload = () => {
        const blob = new Blob([clientConfigText], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${device.name}-wg.conf`;
        a.click();
        URL.revokeObjectURL(url);
    };

    const handleRegenerate = () => {
        setClientKeys(generateMockKeys());
        toast({ title: 'New Keys Generated', description: 'A new private/public key pair has been generated.' });
    }

    return (
        <Sheet open={isOpen} onOpenChange={onClose}>
            <SheetContent className="sm:max-w-lg w-full">
                <SheetHeader>
                    <SheetTitle>WireGuard Client Config</SheetTitle>
                    <SheetDescription>
                        Scan the QR code with your WireGuard mobile app or copy the configuration.
                    </SheetDescription>
                </SheetHeader>
                <div className="py-4 grid grid-cols-1 md:grid-cols-2 gap-6 items-start">
                    <div className="space-y-4">
                        <Textarea
                            readOnly
                            value={clientConfigText}
                            className="h-64 font-mono text-xs bg-muted/50"
                        />
                        <div className="grid grid-cols-2 gap-2">
                             <Button variant="outline" onClick={handleCopy}><Copy className="mr-2"/> Copy</Button>
                             <Button variant="outline" onClick={handleDownload}><Download className="mr-2"/> Download</Button>
                        </div>
                        <Button variant="secondary" className="w-full" onClick={handleRegenerate}><RefreshCw className="mr-2"/> Regenerate Keys</Button>
                    </div>
                    <div className="flex flex-col items-center justify-center p-4 border rounded-lg bg-background">
                       <div className="p-2 bg-white rounded-lg">
                         <QRCode value={clientConfigText} size={200} />
                       </div>
                       <p className="text-xs text-muted-foreground mt-4 text-center">Scan with the WireGuard app</p>
                    </div>
                </div>
                <SheetFooter className="mt-4">
                    <Button variant="outline" onClick={onClose}>Close</Button>
                </SheetFooter>
            </SheetContent>
        </Sheet>
    );
};

export default VpnClientConfigGenerator;